name: Deploy Python Code to AWS Lambda
author: dpo
description: Deploy python 3.8 code to AWS Lambda, lightning quick builds!
inputs:
  function_name:
    description: the Lambda function name
    required: true
  working_directory:
    description: the Lambda function directory
    required: true
  runtime:
    description: the Lambda function runtime
    required: true
  role:
    description: the Lambda function IAM role
    required: true
  handler:
    description: the Lambda function handler
    required: true
  memory:
    description: the Lambda function memory size in MB
    required: true
  timeout:
    description: the Lambda function time limit in seconds
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.function_name }}
    - ${{ inputs.working_directory }}
    - ${{ inputs.runtime }}
    - ${{ inputs.role }}
    - ${{ inputs.handler }}
    - ${{ inputs.memory }}
    - ${{ inputs.timeout }}
branding:
  icon: "cloud-lightning"
  color: "orange"
